language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure: "M017B4T3S7UaMRzlorrTkY8tYQYkDTBmStbIoqzZkIzhepsUh3qrinWu5pGvkId1CzRYwKJbxAo5HeBf+2abWRANpQ0yLMmhCqkD/xT+xZA6hKTsv2uBjtp8cwT9rx3WVuAPmQ7AOWMJts6Pp2HdEuwewzBRM4As/rlnd1Jiz1E/ELuGWuydr0kIYloKOuZpSvtYYdgm9Dncgw+z/vhUFv3gU2rAunX7a57K3APozk/K+vRK+zT4RWyG5qpxPOgGrrB9ES80UAruP5zCktbIKx5dZZ3q1GphCHRWndlhZCXCL9EqMmrKjSXDB3BVseIRnXE5Rwh1IBlPkq7zAiD+aG2/78NsD62KFNF4XkEH9VJxDdJopCDpeQ/1yXZapLOBgiqBZBbrhUrFZIrqvg/iT2PdKxWeWvDEvRnrxFdX3Cr1PmwaXCdk/5UXzno6Hzk8urwEd3hdq4g+JvF5IkQm1nyztdg7pYFlrrSaPxEUNFNcwGO/7Vf9NIZJFp6JYudT6Up5vvTHY/m4I9wYheouwDBpXdR5hsB6RQpd1Iue8vjoibEuzhSKf/krpDTE7fWcAPyVt7ZDAkITwe7gEVq7lO0f8wRb0ATy+cTQ3lN5uOeMZI9UFSZwdfIV3JuYlRmdrIwNJbAP5Xm2fJof8q0YkbfhguJTCgXU6oJAaEwG29o="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh
    - openssl aes-256-cbc -K $encrypted_efba3b7787e2_key -iv $encrypted_efba3b7787e2_iv -in 6D5E5753F12109663BABEED53087CD3324A99FBC.gpg.enc -out 6D5E5753F12109663BABEED53087CD3324A99FBC.gpg -d
    - gpg --import 6D5E5753F12109663BABEED53087CD3324A99FBC.gpg
install:
    - debuild '-k3087CD3324A99FBC'